// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

package echo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EchoResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EchoReverseRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoReverseRequest) Reset()         { *m = EchoReverseRequest{} }
func (m *EchoReverseRequest) String() string { return proto.CompactTextString(m) }
func (*EchoReverseRequest) ProtoMessage()    {}
func (*EchoReverseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{2}
}

func (m *EchoReverseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoReverseRequest.Unmarshal(m, b)
}
func (m *EchoReverseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoReverseRequest.Marshal(b, m, deterministic)
}
func (m *EchoReverseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoReverseRequest.Merge(m, src)
}
func (m *EchoReverseRequest) XXX_Size() int {
	return xxx_messageInfo_EchoReverseRequest.Size(m)
}
func (m *EchoReverseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoReverseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoReverseRequest proto.InternalMessageInfo

func (m *EchoReverseRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EchoReverseResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoReverseResponse) Reset()         { *m = EchoReverseResponse{} }
func (m *EchoReverseResponse) String() string { return proto.CompactTextString(m) }
func (*EchoReverseResponse) ProtoMessage()    {}
func (*EchoReverseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08134aea513e0001, []int{3}
}

func (m *EchoReverseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoReverseResponse.Unmarshal(m, b)
}
func (m *EchoReverseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoReverseResponse.Marshal(b, m, deterministic)
}
func (m *EchoReverseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoReverseResponse.Merge(m, src)
}
func (m *EchoReverseResponse) XXX_Size() int {
	return xxx_messageInfo_EchoReverseResponse.Size(m)
}
func (m *EchoReverseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoReverseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoReverseResponse proto.InternalMessageInfo

func (m *EchoReverseResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "echo.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "echo.EchoResponse")
	proto.RegisterType((*EchoReverseRequest)(nil), "echo.EchoReverseRequest")
	proto.RegisterType((*EchoReverseResponse)(nil), "echo.EchoReverseResponse")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor_08134aea513e0001) }

var fileDescriptor_08134aea513e0001 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x14, 0xb9, 0xb8, 0x5d, 0x93,
	0x33, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf2, 0x53,
	0x2a, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e, 0x1e, 0x88, 0x92,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xac, 0x6a, 0x34, 0xb8, 0x84, 0x20, 0x6a, 0xca, 0x52, 0x8b,
	0x8a, 0x53, 0xf1, 0x99, 0xa6, 0xc9, 0x25, 0x8c, 0xa2, 0x12, 0xb7, 0xa1, 0x46, 0xb5, 0x5c, 0x2c,
	0x20, 0xa5, 0x42, 0xfa, 0x50, 0x5a, 0x50, 0x0f, 0xec, 0x7c, 0x24, 0xf7, 0x4a, 0x09, 0x21, 0x0b,
	0x41, 0x8c, 0x52, 0x62, 0x10, 0x72, 0x81, 0x79, 0x0a, 0x6c, 0x87, 0x90, 0x04, 0xb2, 0x22, 0x64,
	0x07, 0x4a, 0x49, 0x62, 0x91, 0x81, 0x99, 0x92, 0xc4, 0x06, 0x0e, 0x27, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x80, 0x2e, 0x4c, 0x45, 0x35, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EchoClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoReverse(ctx context.Context, in *EchoReverseRequest, opts ...grpc.CallOption) (*EchoReverseResponse, error)
}

type echoClient struct {
	cc *grpc.ClientConn
}

func NewEchoClient(cc *grpc.ClientConn) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/echo.Echo/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoReverse(ctx context.Context, in *EchoReverseRequest, opts ...grpc.CallOption) (*EchoReverseResponse, error) {
	out := new(EchoReverseResponse)
	err := c.cc.Invoke(ctx, "/echo.Echo/EchoReverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
type EchoServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoReverse(context.Context, *EchoReverseRequest) (*EchoReverseResponse, error)
}

// UnimplementedEchoServer can be embedded to have forward compatible implementations.
type UnimplementedEchoServer struct {
}

func (*UnimplementedEchoServer) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (*UnimplementedEchoServer) EchoReverse(ctx context.Context, req *EchoReverseRequest) (*EchoReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoReverse not implemented")
}

func RegisterEchoServer(s *grpc.Server, srv EchoServer) {
	s.RegisterService(&_Echo_serviceDesc, srv)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echo/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoReverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoReverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/echo.Echo/EchoReverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoReverse(ctx, req.(*EchoReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Echo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "echo.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
		{
			MethodName: "EchoReverse",
			Handler:    _Echo_EchoReverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}
