// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baz/baz.proto

package baz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	foo "github.com/syumai/til/proto/package-resolution/foo"
	bar "github.com/syumai/til/proto/package-resolution/foo/bar"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Foo struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_736e657fe5285e51, []int{0}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Baz struct {
	Foo1                 *foo.Foo `protobuf:"bytes,1,opt,name=foo1,proto3" json:"foo1,omitempty"`
	Foo2                 *Foo     `protobuf:"bytes,2,opt,name=foo2,proto3" json:"foo2,omitempty"`
	Bar1                 *bar.Bar `protobuf:"bytes,3,opt,name=bar1,proto3" json:"bar1,omitempty"`
	Bar2                 *bar.Bar `protobuf:"bytes,4,opt,name=bar2,proto3" json:"bar2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Baz) Reset()         { *m = Baz{} }
func (m *Baz) String() string { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()    {}
func (*Baz) Descriptor() ([]byte, []int) {
	return fileDescriptor_736e657fe5285e51, []int{1}
}

func (m *Baz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Baz.Unmarshal(m, b)
}
func (m *Baz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Baz.Marshal(b, m, deterministic)
}
func (m *Baz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Baz.Merge(m, src)
}
func (m *Baz) XXX_Size() int {
	return xxx_messageInfo_Baz.Size(m)
}
func (m *Baz) XXX_DiscardUnknown() {
	xxx_messageInfo_Baz.DiscardUnknown(m)
}

var xxx_messageInfo_Baz proto.InternalMessageInfo

func (m *Baz) GetFoo1() *foo.Foo {
	if m != nil {
		return m.Foo1
	}
	return nil
}

func (m *Baz) GetFoo2() *Foo {
	if m != nil {
		return m.Foo2
	}
	return nil
}

func (m *Baz) GetBar1() *bar.Bar {
	if m != nil {
		return m.Bar1
	}
	return nil
}

func (m *Baz) GetBar2() *bar.Bar {
	if m != nil {
		return m.Bar2
	}
	return nil
}

func init() {
	proto.RegisterType((*Foo)(nil), "foo.baz.Foo")
	proto.RegisterType((*Baz)(nil), "foo.baz.Baz")
}

func init() { proto.RegisterFile("baz/baz.proto", fileDescriptor_736e657fe5285e51) }

var fileDescriptor_736e657fe5285e51 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0x59, 0xd4, 0x8d, 0x2e, 0x48, 0x2e, 0x86, 0xc5, 0xc3, 0xb2, 0x27, 0x2f, 0x26,
	0x6c, 0x04, 0xf1, 0xdc, 0x43, 0x1f, 0xa0, 0x47, 0x6f, 0x33, 0xa5, 0xad, 0xc1, 0xd6, 0x29, 0x69,
	0x7a, 0x30, 0x6f, 0xe0, 0x5b, 0x4b, 0xc6, 0x22, 0x78, 0xd8, 0xdb, 0x9f, 0xff, 0xfb, 0xc8, 0x30,
	0x23, 0x77, 0x08, 0xc9, 0x22, 0x24, 0x33, 0x05, 0x8a, 0xa4, 0xae, 0x3a, 0x22, 0x83, 0x90, 0xf6,
	0xdb, 0x1c, 0xb8, 0xdb, 0xef, 0x10, 0x82, 0x45, 0x08, 0xbf, 0xcf, 0xe3, 0xbd, 0x14, 0x15, 0x91,
	0xba, 0x93, 0x62, 0x9c, 0x7b, 0x5d, 0x1c, 0x8a, 0xc7, 0x6d, 0x9d, 0xe3, 0xf1, 0xbb, 0x90, 0xa2,
	0x84, 0xa4, 0x1e, 0xe4, 0xa6, 0x23, 0x3a, 0x31, 0xba, 0x71, 0xd7, 0x26, 0xff, 0x54, 0x11, 0xd5,
	0xdc, 0xaa, 0x03, 0x53, 0xa7, 0x2f, 0x98, 0xde, 0x9a, 0x75, 0xe0, 0x9f, 0xe1, 0xb2, 0x81, 0x10,
	0x4e, 0x5a, 0xfc, 0x33, 0x82, 0x29, 0x21, 0xd4, 0x4c, 0x56, 0xc3, 0xe9, 0xcd, 0x19, 0xc3, 0x95,
	0xaf, 0x6f, 0x2f, 0xbd, 0x8f, 0xef, 0x0b, 0x9a, 0x86, 0x46, 0x3b, 0x7f, 0x2d, 0x23, 0x78, 0x1b,
	0xfd, 0x60, 0x79, 0x07, 0x3b, 0x41, 0xf3, 0x01, 0x7d, 0xfb, 0x14, 0xda, 0x99, 0x86, 0x25, 0x7a,
	0xfa, 0xb4, 0x1d, 0x51, 0xbe, 0x03, 0x5e, 0xb2, 0xf1, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x44, 0xce, 0xbf, 0x19, 0x01, 0x00, 0x00,
}
