// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bar/bar.proto

package bar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	foo "github.com/syumai/til/proto/package-resolution/foo"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bar struct {
	Foo1                 *foo.Foo `protobuf:"bytes,1,opt,name=foo1,proto3" json:"foo1,omitempty"`
	Foo2                 *foo.Foo `protobuf:"bytes,2,opt,name=foo2,proto3" json:"foo2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bar) Reset()         { *m = Bar{} }
func (m *Bar) String() string { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()    {}
func (*Bar) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b43622d8d3cde07, []int{0}
}

func (m *Bar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bar.Unmarshal(m, b)
}
func (m *Bar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bar.Marshal(b, m, deterministic)
}
func (m *Bar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bar.Merge(m, src)
}
func (m *Bar) XXX_Size() int {
	return xxx_messageInfo_Bar.Size(m)
}
func (m *Bar) XXX_DiscardUnknown() {
	xxx_messageInfo_Bar.DiscardUnknown(m)
}

var xxx_messageInfo_Bar proto.InternalMessageInfo

func (m *Bar) GetFoo1() *foo.Foo {
	if m != nil {
		return m.Foo1
	}
	return nil
}

func (m *Bar) GetFoo2() *foo.Foo {
	if m != nil {
		return m.Foo2
	}
	return nil
}

func init() {
	proto.RegisterType((*Bar)(nil), "foo.bar.Bar")
}

func init() { proto.RegisterFile("bar/bar.proto", fileDescriptor_6b43622d8d3cde07) }

var fileDescriptor_6b43622d8d3cde07 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x2c, 0xd2,
	0x4f, 0x4a, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xcb, 0xcf, 0xd7, 0x4b,
	0x4a, 0x2c, 0x92, 0xe2, 0x04, 0x31, 0xc0, 0x62, 0x4a, 0x8e, 0x5c, 0xcc, 0x4e, 0x89, 0x45, 0x42,
	0x32, 0x5c, 0x2c, 0x69, 0xf9, 0xf9, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x1c, 0x7a,
	0x20, 0x05, 0x6e, 0xf9, 0xf9, 0x41, 0x60, 0x51, 0xa8, 0xac, 0x91, 0x04, 0x13, 0x16, 0x59, 0x23,
	0x27, 0x8b, 0x28, 0xb3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2,
	0xca, 0xd2, 0xdc, 0xc4, 0x4c, 0xfd, 0x92, 0xcc, 0x1c, 0x7d, 0xb0, 0x0d, 0xfa, 0x05, 0x89, 0xc9,
	0xd9, 0x89, 0xe9, 0xa9, 0xba, 0x45, 0xa9, 0xc5, 0xf9, 0x39, 0xa5, 0x25, 0x99, 0xf9, 0x79, 0xfa,
	0x69, 0xf9, 0xf9, 0x20, 0x67, 0x25, 0xb1, 0x81, 0x55, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x38, 0x5d, 0x1d, 0x23, 0xa8, 0x00, 0x00, 0x00,
}
